// Predefined plant database with care requirements
export const PLANT_DATABASE = [
  // Houseplants
  {
    id: 'monstera',
    name: 'Monstera Deliciosa',
    type: 'houseplant',
    wateringFrequency: 7, // days
    fertilizingFrequency: 30, // days
    fertilizingSeason: 'spring-summer', // spring, summer, fall, winter, spring-summer, all-year
    pruningFrequency: 90, // days
    repottingFrequency: 365, // days
    mistingFrequency: 3, // days
    lightRotationFrequency: 7, // days
    pestCheckFrequency: 14, // days
    careLevel: 'easy',
    description: 'Large, glossy leaves with natural holes. Perfect for bright, indirect light.',
  },
  {
    id: 'snake-plant',
    name: 'Snake Plant',
    type: 'houseplant',
    wateringFrequency: 14,
    fertilizingFrequency: 60,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: 730,
    mistingFrequency: null,
    lightRotationFrequency: 14,
    pestCheckFrequency: 30,
    careLevel: 'very-easy',
    description: 'Extremely low maintenance. Thrives on neglect.',
  },
  {
    id: 'pothos',
    name: 'Golden Pothos',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 5,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Fast-growing trailing vine. Great for beginners.',
  },
  {
    id: 'fiddle-leaf',
    name: 'Fiddle Leaf Fig',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Large, violin-shaped leaves. Needs consistent care.',
  },
  {
    id: 'spider-plant',
    name: 'Spider Plant',
    type: 'houseplant',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Produces baby plantlets. Very forgiving.',
  },
  {
    id: 'peace-lily',
    name: 'Peace Lily',
    type: 'houseplant',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'White flowers and dark green leaves. Loves humidity.',
  },
  {
    id: 'rubber-plant',
    name: 'Rubber Plant',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Glossy, dark green leaves. Low maintenance.',
  },
  {
    id: 'zz-plant',
    name: 'ZZ Plant',
    type: 'houseplant',
    wateringFrequency: 14,
    fertilizingFrequency: 60,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: 730,
    mistingFrequency: null,
    lightRotationFrequency: 14,
    pestCheckFrequency: 30,
    careLevel: 'very-easy',
    description: 'Nearly indestructible. Perfect for low light.',
  },
  // Herbs
  {
    id: 'basil',
    name: 'Basil',
    type: 'herb',
    wateringFrequency: 2,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Aromatic culinary herb. Pinch flowers to encourage growth.',
  },
  {
    id: 'mint',
    name: 'Mint',
    type: 'herb',
    wateringFrequency: 2,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 14,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Fast-growing and invasive. Keep in containers.',
  },
  {
    id: 'rosemary',
    name: 'Rosemary',
    type: 'herb',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 30,
    repottingFrequency: 365,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Woody, aromatic herb. Prefers well-draining soil.',
  },
  {
    id: 'thyme',
    name: 'Thyme',
    type: 'herb',
    wateringFrequency: 3,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 30,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Low-growing herb. Great for cooking.',
  },
  // Outdoor/Garden
  {
    id: 'tomato',
    name: 'Tomato',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'moderate',
    description: 'Requires consistent watering and support.',
  },
  {
    id: 'pepper',
    name: 'Bell Pepper',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 14,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'moderate',
    description: 'Warm-season crop. Needs full sun.',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 21,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'easy',
    description: 'Cool-season crop. Harvest outer leaves.',
  },
  // More Houseplants
  {
    id: 'areca-palm',
    name: 'Areca Palm',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Feathery, arching fronds. Loves bright, indirect light and humidity.',
  },
  {
    id: 'aloe-vera',
    name: 'Aloe Vera',
    type: 'houseplant',
    wateringFrequency: 14,
    fertilizingFrequency: 60,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: 365,
    mistingFrequency: null,
    lightRotationFrequency: 14,
    pestCheckFrequency: 30,
    careLevel: 'very-easy',
    description: 'Succulent with medicinal properties. Very low maintenance.',
  },
  {
    id: 'jade-plant',
    name: 'Jade Plant',
    type: 'houseplant',
    wateringFrequency: 10,
    fertilizingFrequency: 60,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: null,
    lightRotationFrequency: 14,
    pestCheckFrequency: 30,
    careLevel: 'easy',
    description: 'Thick, glossy leaves. Symbol of good luck. Very forgiving.',
  },
  {
    id: 'philodendron',
    name: 'Philodendron',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Heart-shaped leaves. Fast-growing and adaptable.',
  },
  {
    id: 'dracaena',
    name: 'Dracaena',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Striking striped leaves. Tolerates low light well.',
  },
  {
    id: 'boston-fern',
    name: 'Boston Fern',
    type: 'houseplant',
    wateringFrequency: 3,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 1,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Lush, feathery fronds. Requires high humidity.',
  },
  {
    id: 'english-ivy',
    name: 'English Ivy',
    type: 'houseplant',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Trailing vine with lobed leaves. Great for hanging baskets.',
  },
  {
    id: 'chinese-evergreen',
    name: 'Chinese Evergreen',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Variegated leaves. Thrives in low to medium light.',
  },
  {
    id: 'prayer-plant',
    name: 'Prayer Plant',
    type: 'houseplant',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Leaves fold up at night. Needs high humidity.',
  },
  {
    id: 'bird-of-paradise',
    name: 'Bird of Paradise',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Large, tropical leaves. Needs bright light to flower.',
  },
  {
    id: 'calathea',
    name: 'Calathea',
    type: 'houseplant',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Beautiful patterned leaves. Requires consistent moisture.',
  },
  {
    id: 'pothos-neon',
    name: 'Neon Pothos',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 5,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Bright chartreuse leaves. Very easy to care for.',
  },
  {
    id: 'string-of-pearls',
    name: 'String of Pearls',
    type: 'houseplant',
    wateringFrequency: 10,
    fertilizingFrequency: 60,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: 365,
    mistingFrequency: null,
    lightRotationFrequency: 14,
    pestCheckFrequency: 30,
    careLevel: 'moderate',
    description: 'Trailing succulent with bead-like leaves. Bright indirect light.',
  },
  {
    id: 'rubber-tree',
    name: 'Rubber Tree',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Large, glossy leaves. Can grow quite tall indoors.',
  },
  {
    id: 'swiss-cheese-plant',
    name: 'Swiss Cheese Plant',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Similar to Monstera. Large leaves with holes.',
  },
  {
    id: 'snake-plant-laurentii',
    name: 'Snake Plant Laurentii',
    type: 'houseplant',
    wateringFrequency: 14,
    fertilizingFrequency: 60,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: 730,
    mistingFrequency: null,
    lightRotationFrequency: 14,
    pestCheckFrequency: 30,
    careLevel: 'very-easy',
    description: 'Yellow-edged variety. Extremely low maintenance.',
  },
  {
    id: 'pothos-marble',
    name: 'Marble Queen Pothos',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 5,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Variegated white and green leaves. Fast grower.',
  },
  {
    id: 'bamboo-palm',
    name: 'Bamboo Palm',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Graceful palm with bamboo-like stems. Loves humidity.',
  },
  {
    id: 'yucca',
    name: 'Yucca',
    type: 'houseplant',
    wateringFrequency: 10,
    fertilizingFrequency: 60,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: 365,
    mistingFrequency: null,
    lightRotationFrequency: 14,
    pestCheckFrequency: 30,
    careLevel: 'easy',
    description: 'Sword-like leaves. Very drought tolerant.',
  },
  {
    id: 'schefflera',
    name: 'Schefflera',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Umbrella-like leaves. Fast-growing tree-like plant.',
  },
  // More Herbs
  {
    id: 'oregano',
    name: 'Oregano',
    type: 'herb',
    wateringFrequency: 3,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 14,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Mediterranean herb. Pinch flowers to maintain flavor.',
  },
  {
    id: 'parsley',
    name: 'Parsley',
    type: 'herb',
    wateringFrequency: 2,
    fertilizingFrequency: 21,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Biennial herb. Harvest outer leaves regularly.',
  },
  {
    id: 'cilantro',
    name: 'Cilantro',
    type: 'herb',
    wateringFrequency: 2,
    fertilizingFrequency: 21,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Fast-growing. Harvest before it bolts (flowers).',
  },
  {
    id: 'sage',
    name: 'Sage',
    type: 'herb',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 30,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Woody perennial. Drought tolerant once established.',
  },
  {
    id: 'chives',
    name: 'Chives',
    type: 'herb',
    wateringFrequency: 3,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 14,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Onion-flavored leaves. Cut back after flowering.',
  },
  {
    id: 'dill',
    name: 'Dill',
    type: 'herb',
    wateringFrequency: 2,
    fertilizingFrequency: 21,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Feathery leaves. Harvest before flowering for best flavor.',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    type: 'herb',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Aromatic purple flowers. Needs well-draining soil.',
  },
  {
    id: 'lemon-balm',
    name: 'Lemon Balm',
    type: 'herb',
    wateringFrequency: 3,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 14,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Lemon-scented leaves. Great for tea. Can be invasive.',
  },
  // More Garden Vegetables
  {
    id: 'cucumber',
    name: 'Cucumber',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'moderate',
    description: 'Vining crop. Needs consistent moisture and support.',
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'easy',
    description: 'Fast-growing summer squash. Harvest when small.',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Root vegetable. Needs loose, deep soil.',
  },
  {
    id: 'radish',
    name: 'Radish',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 21,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'easy',
    description: 'Fast-growing root crop. Ready in 3-4 weeks.',
  },
  {
    id: 'spinach',
    name: 'Spinach',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 21,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'easy',
    description: 'Cool-season leafy green. Harvest outer leaves.',
  },
  {
    id: 'kale',
    name: 'Kale',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 21,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'easy',
    description: 'Cold-hardy superfood. Harvest outer leaves.',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 21,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 30,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'moderate',
    description: 'Perennial fruit. Remove runners to focus energy.',
  },
  {
    id: 'basil-thai',
    name: 'Thai Basil',
    type: 'herb',
    wateringFrequency: 2,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Licorice-flavored basil. Great for Asian cuisine.',
  },
  // Outdoor Plants
  {
    id: 'hosta',
    name: 'Hosta',
    type: 'outdoor',
    wateringFrequency: 3,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Shade-loving perennial. Large, attractive leaves.',
  },
  {
    id: 'hydrangea',
    name: 'Hydrangea',
    type: 'outdoor',
    wateringFrequency: 3,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'moderate',
    description: 'Large flower clusters. Color depends on soil pH.',
  },
  {
    id: 'roses',
    name: 'Roses',
    type: 'outdoor',
    wateringFrequency: 3,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 30,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'moderate',
    description: 'Classic flowering shrub. Deadhead regularly.',
  },
  {
    id: 'lavender-outdoor',
    name: 'Lavender (Outdoor)',
    type: 'outdoor',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Drought-tolerant perennial. Full sun required.',
  },
];

export const TASK_TYPES = {
  WATERING: 'watering',
  FERTILIZING: 'fertilizing',
  PRUNING: 'pruning',
  REPOTTING: 'repotting',
  MISTING: 'misting',
  LIGHT_ROTATION: 'light_rotation',
  PEST_CHECK: 'pest_check',
};

export const getTaskLabel = (taskType) => {
  const labels = {
    [TASK_TYPES.WATERING]: 'Water',
    [TASK_TYPES.FERTILIZING]: 'Fertilize',
    [TASK_TYPES.PRUNING]: 'Prune',
    [TASK_TYPES.REPOTTING]: 'Repot',
    [TASK_TYPES.MISTING]: 'Mist',
    [TASK_TYPES.LIGHT_ROTATION]: 'Rotate for Light',
    [TASK_TYPES.PEST_CHECK]: 'Pest Check',
  };
  return labels[taskType] || taskType;
};

export const getTaskIcon = (taskType) => {
  // This will be used with lucide-react icons
  const icons = {
    [TASK_TYPES.WATERING]: 'Droplet',
    [TASK_TYPES.FERTILIZING]: 'Flower',
    [TASK_TYPES.PRUNING]: 'Scissors',
    [TASK_TYPES.REPOTTING]: 'Package',
    [TASK_TYPES.MISTING]: 'Cloud',
    [TASK_TYPES.LIGHT_ROTATION]: 'Sun',
    [TASK_TYPES.PEST_CHECK]: 'Search',
  };
  return icons[taskType] || 'Circle';
};

