// Predefined plant database with care requirements
export const PLANT_DATABASE = [
  // Houseplants
  {
    id: 'monstera',
    name: 'Monstera Deliciosa',
    type: 'houseplant',
    wateringFrequency: 7, // days
    fertilizingFrequency: 30, // days
    fertilizingSeason: 'spring-summer', // spring, summer, fall, winter, spring-summer, all-year
    pruningFrequency: 90, // days
    repottingFrequency: 365, // days
    mistingFrequency: 3, // days
    lightRotationFrequency: 7, // days
    pestCheckFrequency: 14, // days
    careLevel: 'easy',
    description: 'Large, glossy leaves with natural holes. Perfect for bright, indirect light.',
  },
  {
    id: 'snake-plant',
    name: 'Snake Plant',
    type: 'houseplant',
    wateringFrequency: 14,
    fertilizingFrequency: 60,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: 730,
    mistingFrequency: null,
    lightRotationFrequency: 14,
    pestCheckFrequency: 30,
    careLevel: 'very-easy',
    description: 'Extremely low maintenance. Thrives on neglect.',
  },
  {
    id: 'pothos',
    name: 'Golden Pothos',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 5,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Fast-growing trailing vine. Great for beginners.',
  },
  {
    id: 'fiddle-leaf',
    name: 'Fiddle Leaf Fig',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Large, violin-shaped leaves. Needs consistent care.',
  },
  {
    id: 'spider-plant',
    name: 'Spider Plant',
    type: 'houseplant',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Produces baby plantlets. Very forgiving.',
  },
  {
    id: 'peace-lily',
    name: 'Peace Lily',
    type: 'houseplant',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 60,
    repottingFrequency: 365,
    mistingFrequency: 2,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'White flowers and dark green leaves. Loves humidity.',
  },
  {
    id: 'rubber-plant',
    name: 'Rubber Plant',
    type: 'houseplant',
    wateringFrequency: 7,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 90,
    repottingFrequency: 365,
    mistingFrequency: 3,
    lightRotationFrequency: 7,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Glossy, dark green leaves. Low maintenance.',
  },
  {
    id: 'zz-plant',
    name: 'ZZ Plant',
    type: 'houseplant',
    wateringFrequency: 14,
    fertilizingFrequency: 60,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: 730,
    mistingFrequency: null,
    lightRotationFrequency: 14,
    pestCheckFrequency: 30,
    careLevel: 'very-easy',
    description: 'Nearly indestructible. Perfect for low light.',
  },
  // Herbs
  {
    id: 'basil',
    name: 'Basil',
    type: 'herb',
    wateringFrequency: 2,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Aromatic culinary herb. Pinch flowers to encourage growth.',
  },
  {
    id: 'mint',
    name: 'Mint',
    type: 'herb',
    wateringFrequency: 2,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 14,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 7,
    careLevel: 'easy',
    description: 'Fast-growing and invasive. Keep in containers.',
  },
  {
    id: 'rosemary',
    name: 'Rosemary',
    type: 'herb',
    wateringFrequency: 5,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 30,
    repottingFrequency: 365,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 14,
    careLevel: 'moderate',
    description: 'Woody, aromatic herb. Prefers well-draining soil.',
  },
  {
    id: 'thyme',
    name: 'Thyme',
    type: 'herb',
    wateringFrequency: 3,
    fertilizingFrequency: 30,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 30,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 14,
    careLevel: 'easy',
    description: 'Low-growing herb. Great for cooking.',
  },
  // Outdoor/Garden
  {
    id: 'tomato',
    name: 'Tomato',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 7,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'moderate',
    description: 'Requires consistent watering and support.',
  },
  {
    id: 'pepper',
    name: 'Bell Pepper',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 14,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: 14,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'moderate',
    description: 'Warm-season crop. Needs full sun.',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    type: 'garden',
    wateringFrequency: 2,
    fertilizingFrequency: 21,
    fertilizingSeason: 'spring-summer',
    pruningFrequency: null,
    repottingFrequency: null,
    mistingFrequency: null,
    lightRotationFrequency: null,
    pestCheckFrequency: 3,
    careLevel: 'easy',
    description: 'Cool-season crop. Harvest outer leaves.',
  },
];

export const TASK_TYPES = {
  WATERING: 'watering',
  FERTILIZING: 'fertilizing',
  PRUNING: 'pruning',
  REPOTTING: 'repotting',
  MISTING: 'misting',
  LIGHT_ROTATION: 'light_rotation',
  PEST_CHECK: 'pest_check',
};

export const getTaskLabel = (taskType) => {
  const labels = {
    [TASK_TYPES.WATERING]: 'Water',
    [TASK_TYPES.FERTILIZING]: 'Fertilize',
    [TASK_TYPES.PRUNING]: 'Prune',
    [TASK_TYPES.REPOTTING]: 'Repot',
    [TASK_TYPES.MISTING]: 'Mist',
    [TASK_TYPES.LIGHT_ROTATION]: 'Rotate for Light',
    [TASK_TYPES.PEST_CHECK]: 'Pest Check',
  };
  return labels[taskType] || taskType;
};

export const getTaskIcon = (taskType) => {
  // This will be used with lucide-react icons
  const icons = {
    [TASK_TYPES.WATERING]: 'Droplet',
    [TASK_TYPES.FERTILIZING]: 'Flower',
    [TASK_TYPES.PRUNING]: 'Scissors',
    [TASK_TYPES.REPOTTING]: 'Package',
    [TASK_TYPES.MISTING]: 'Cloud',
    [TASK_TYPES.LIGHT_ROTATION]: 'Sun',
    [TASK_TYPES.PEST_CHECK]: 'Search',
  };
  return icons[taskType] || 'Circle';
};

